# Copyright (c) Jiaqi Liu
name: Documentation CI/CD

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  mk-yml-style-check:
    uses: QubitPi/hashicorp-dev-portal/.github/workflows/doc-ci-cd.yml@master
