name: Unit Test Run
on:
  workflow_call:
    inputs:
      concurrency_group_prefix:
        default: pr
        required: false
        type: string
      package:
        required: true
        type: string
      terraform_version:
        required: true
        type: string

concurrency:
  group: ${{ inputs.concurrency_group_prefix }}-unit-${{ inputs.package }}-${{ inputs.terraform_version }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  cancel-previous:
    name: |
      Cancel Previous Runs In Order to Allocate Action Resources Immediately for Current Run
      Learned from https://github.com/QubitPi/google-flax/blob/master/.github/workflows/build.yml
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.10.1
        if: ${{github.ref != 'refs/head/master'}}
        with:
          access_token: ${{ github.token }}

  unit-test:
    runs-on:
      - ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    env:
      CHECKPOINT_DISABLE: "1"
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: "Add Git safe.directory" # Go 1.18+ started embedding repo info in the build and e.g. building @cdktf/hcl2json fails without this
        run: git config --global --add safe.directory /__w/hashicorp-terraform-cdk/hashicorp-terraform-cdk
      - name: ensure correct user
        run: chown -R root /__w/hashicorp-terraform-cdk

      # Setup caches for yarn, terraform, go, and provider schema
      - name: Get cache directory paths
        id: global-cache-dir-path
        run: |
          echo "yarn=$(yarn cache dir)" >> $GITHUB_OUTPUT
          mkdir -p /usr/local/share/.cache/go
          echo "go=/usr/local/share/.cache/go" >> $GITHUB_OUTPUT
          mkdir -p /usr/local/share/.cache/providerSchema
          echo "providerSchema=/usr/local/share/.cache/providerSchema" >> $GITHUB_OUTPUT
      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ${{ steps.global-cache-dir-path.outputs.yarn }}
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-unit
          restore-keys: |
            yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-
            yarn-${{ runner.os }}-
      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ${{ steps.global-cache-dir-path.outputs.go }}
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}-unit
          restore-keys: |
            go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}-
            go-${{ runner.os }}-
      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ${{ steps.global-cache-dir-path.outputs.providerSchema }}
          key: providerSchema-${{ runner.os }}-${{ inputs.terraform_version }}-unit-${{ inputs.package }}

      - name: installing dependencies
        run: |
          yarn install --frozen-lockfile --prefer-offline
      - name: compile
        run: |
          tools/align-version.sh
          yarn build
          yarn package
        env:
          TERRAFORM_BINARY_NAME: "terraform${{ inputs.terraform_version }}"
          GOCACHE: ${{ steps.global-cache-dir-path.outputs.go }}
      - name: test
        run: |
          unset TF_PLUGIN_CACHE_DIR
          npx lerna run --scope '${{ inputs.package }}' test:ci
        env:
          TERRAFORM_BINARY_NAME: "terraform${{ inputs.terraform_version }}"
          GOCACHE: ${{ steps.global-cache-dir-path.outputs.go }}
          CDKTF_EXPERIMENTAL_PROVIDER_SCHEMA_CACHE_PATH: ${{ steps.global-cache-dir-path.outputs.providerSchema }}
